name: 'import-data'
description: 'Import and validate observability packs'
author: 'New Relic'
inputs:
  nr-account-id:
    description: "Account id for new relic account"
    required: true
  nr-api-key:
    description: "Token to use for authentication to GitHub APIs"
    required: true
  pack-to-import:
    description: "Name of the desired pack (lowercase). Example: mysql"
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
