name: Validate Packs

on: [push, workflow_dispatch, pull_request]

jobs:
  validate-packs:
    name: Validate Packs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12
  
      - name: Install dependencies
        run: yarn install

      - name: Validate files
        id: validate-files
        run: yarn validate-packs 
